# Generated by Django 2.1.9 on 2019-06-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190416_1027'),
        ('shop', '0004_auto_20190509_1634'),
    ]

    operations = [
    ]
